### ISSUE TITLE
Inline/Squash to struct with pointer fails

### ISSUE THREAD

**Issue by urso** [urso/ucfg#13]
failed: (assert) require map or struct when inling 'Proxy' (*transport.ProxyConfig) accessing config

Removing the '*' from type makes parsing succeed.

Questions:
- We want to support pointers when unpacking inlined structs?
- How to treat inlined struct in case all fields are missing in config file?

**Comment by andrewkroh** [comment]
> We want to support pointers when unpacking inlined structs?

I'm OK with not supporting it, I didn't think it was supported anyways (some of the other packages don't support it as I recall).

> How to treat inlined struct in case all fields are missing in config file?

If it's not a pointer then I guess the only choice is leave it as its zero value.
