### ISSUE TITLE
requiredValidator should check for empty strings

### ISSUE THREAD

**Issue by andrewkroh** [urso/ucfg#20]
Currently the [`requiredValidator`](https://github.com/urso/ucfg/blob/master/validator.go#L252) checks for non-nil. I think it should check the type and verify strings are not empty, which to me means checking `strings.TrimSpace(in) != ""`.

**Comment by andrewkroh** [comment]
And what about slices? Should we also check for `len(in) > 0`?

**Comment by urso** [comment]
I think here is an overlap between `nonzero` and `required` keyword. Even `min` and `max` might be loverloaded to check string/array sizes.

Regarding slices: there is a difference between passing an empty slice and not passing a slice at all. Right now required will catch the later.

Will update required to check:
- string being not ""   intending: require requires string to be present and not empty
- pointers being set intending: pointers to struct must be set
- length of slice > 0 intending: array must be present at least one entry is required.

Will update nonzero to check:
- string being not "" intending: if present it must not be empty
- length of slice > 0: if array/slice present it must not be empty.

**Comment by andrewkroh** [comment]
The proposed changes SGTM.
