### ISSUE TITLE
Using NewFrom with a struct containing a time.Duration

### ISSUE THREAD

**Issue by andrewkroh** [urso/ucfg#25]
It looks like there maybe an issue interpreting the value of `time.Duration` fields inside of structs.

Test case:

```
type TestStruct struct {
	Timeout time.Duration
}

func TestUcfgStructWithDuration(t *testing.T) {
	input := TestStruct{
		Timeout: time.Second,
	}
	c, err := ucfg.NewFrom(input)

	output := TestStruct{}
	err = c.Unpack(&output)
	if err != nil {
		t.Fatal(err)
	}

	assert.Equal(t, input.Timeout, output.Timeout)
}
```

Output:

```

	Error Trace:	my_test.go:239
	Error:		Not equal: 1000000000 (expected)
			        != 1000000000000000000 (actual)
```

**Comment by urso** [comment]
time.Duration is basically an alias for uint64. Due to ucfg not explicitly handle time.Duration it will be interpreted as number. When doing Unpack the number (that used to be in `ns`) is interpreted in seconds.
